name = "aiken-lang/custom_validators"
version = "0.0.0"
compiler = "v1.1.2"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/custom_validators'"

[repository]
user = "aiken-lang"
project = "custom_validators"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.1-beta"
source = "github"

[config]
